name = "zuno-api"
main = "src/pulse-index.js"
compatibility_date = "2026-08-27"

[[d1_databases]]
binding = "DB"
database_name = "zuno-db"
database_id = "ce0472e8-1fcd-49f0-a9cf-b7f6ae8fc48c"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
