import React,{useEffect,useMemo,useRef,useState} from 'react';
import * as ReactDOM from 'react-dom/client';
import {Search,Send,Users,Settings,LogOut,Camera,X,MessageCircle,Plus,Menu} from 'lucide-react';
import './styles.css';
import {api,clearSession,getSession,saveSession} from './lib/api';

function initials(name='User'){return name.split(/\s+/).filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function Avatar({user,large=false}){const src=user?.avatar||'';return <div className={large?'avatar large-avatar':'avatar'}>{src?<img src={src} alt="Profile"/>:initials(user?.name)}</div>}

function Auth({onAuth}){
 const [mode,setMode]=useState('login'),[name,setName]=useState(''),[phone,setPhone]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=mode==='login'?await api.login(phone,password):await api.register(name,phone,password);saveSession(r);onAuth(r.user)}catch(e){setError(e.message||'Unable to continue')}finally{setBusy(false)}}
 return <div className="auth"><div className="auth-card"><div className="logo auth-logo">Z</div><h1>Welcome to ZUNO</h1><p>Connect. Chat. Share.</p><div className="auth-tabs"><button className={mode==='login'?'on':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'on':''} onClick={()=>setMode('register')}>Create account</button></div><form onSubmit={submit}>{mode==='register'&&<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/>}<input required type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number e.g. 0712 345 678"/><input required minLength="6" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (6+ characters)"/>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create my ZUNO account'}</button></form><small>Your phone number is your ZUNO account identifier.</small></div></div>
}

function ProfileEditor({me,onClose,onSaved}){
 const [name,setName]=useState(me.name),[photo,setPhoto]=useState(me.avatar||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),input=useRef(null);
 function choose(e){const f=e.target.files?.[0];if(!f)return;if(f.size>1000000){setError('Choose an image under 1MB.');return}const r=new FileReader();r.onload=()=>setPhoto(String(r.result));r.readAsDataURL(f)}
 async function save(){setBusy(true);setError('');try{const u=await api.updateMe({name:name.trim(),avatar:photo});onSaved(u);onClose()}catch(e){setError(e.message||'Unable to save')}finally{setBusy(false)}}
 return <div className="modal-backdrop"><div className="profile-modal"><button className="modal-close" onClick={onClose}><X/></button><h2>Your profile</h2><div className="profile-large"><Avatar user={{name,avatar:photo}} large/><button className="photo-button" onClick={()=>input.current?.click()}><Camera size={16}/> Choose photo</button><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={choose}/></div><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Phone number<input value={me.phone} readOnly/></label>{error&&<div className="error">{error}</div>}<div className="profile-actions"><button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save changes'}</button></div></div></div>
}

function App(){
 const session=getSession();
 const [me,setMe]=useState(session?.user||null),[people,setPeople]=useState([]),[active,setActive]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[search,setSearch]=useState(''),[profileOpen,setProfileOpen]=useState(false),[mobile,setMobile]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!me)return;api.users().then(setPeople).catch(e=>setError(e.message))},[me]);
 useEffect(()=>{if(!me||!active)return;let alive=true;const load=async()=>{try{const rows=await api.messages(active.id);if(alive)setMessages(rows)}catch(e){if(alive)setError(e.message)}};load();const id=setInterval(load,2000);return()=>{alive=false;clearInterval(id)}},[me,active]);
 const filtered=useMemo(()=>people.filter(p=>p.name?.toLowerCase().includes(search.toLowerCase())||p.phone?.includes(search)),[people,search]);
 async function openChat(p){setActive(p);setMobile(false);try{setMessages(await api.messages(p.id))}catch(e){setError(e.message)}}
 async function send(){const body=text.trim();if(!body||!active)return;try{const m=await api.sendMessage(active.id,body);setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,m]);setText('')}catch(e){setError(e.message)}}
 async function signOut(){try{await api.logout()}catch{}clearSession();setMe(null);setActive(null);setMessages([])}
 if(!me)return <Auth onAuth={u=>{setMe(u);api.users().then(setPeople).catch(()=>{})}}/>;
 return <><div className="app"><aside className={`sidebar ${mobile?'mobile-open':''}`}><div className="brand"><div className="logo">Z</div><span>ZUNO</span><button className="close" onClick={()=>setMobile(false)}><X size={20}/></button></div><button className="profile" onClick={()=>setProfileOpen(true)}><Avatar user={me}/><div><b>{me.name}</b><small>{me.phone}</small></div></button><div className="tabs"><button className="active"><MessageCircle size={18}/> Chats</button><button><Users size={18}/> Groups</button></div><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people"/></div><div className="chat-list">{filtered.map(p=><button className={`chat-row ${active?.id===p.id?'selected':''}`} key={p.id} onClick={()=>openChat(p)}><Avatar user={p}/><div className="chat-info"><b>{p.name}</b><p>{p.phone}</p></div></button>)}{filtered.length===0&&<div className="empty-chat">No other ZUNO users yet.</div>}</div><button className="new-chat" onClick={()=>filtered[0]&&openChat(filtered[0])}><Plus size={18}/> New conversation</button><div className="side-bottom"><button onClick={()=>setProfileOpen(true)}><Settings size={19}/> Profile & settings</button><button onClick={signOut}><LogOut size={19}/> Sign out</button></div></aside><main className="chat">{active?<><header className="chat-head"><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><Avatar user={active}/><div className="head-info"><b>{active.name}</b><span>Available</span></div></header><section className="messages"><div className="day">TODAY</div>{messages.map(m=><div key={m.id} className={`bubble-wrap ${m.sender_id===me.id?'mine':''}`}><div className="bubble">{m.body}</div></div>)}{messages.length===0&&<div className="empty-chat">No messages yet. Say hello 👋</div>}</section><div className="composer"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Write a message..."/><button className="send" onClick={send}><Send size={18}/></button></div></>:<div className="empty-state"><div className="logo">Z</div><h2>Welcome to ZUNO</h2><p>Select someone to start chatting.</p></div>}{error&&<div className="error toast">{error}<button onClick={()=>setError('')}><X size={14}/></button></div>}</main></div>{profileOpen&&<ProfileEditor me={me} onClose={()=>setProfileOpen(false)} onSaved={u=>{setMe(u);saveSession({...getSession(),user:u})}}/>}</>
}

ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
